networks:
  forgejo:
    external: false

services:
  server:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:11
    restart: always
    networks:
      - forgejo
    environment:
      - USER_UID=501
      - USER_GID=20
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3443:3000"
      - "222:22"
